spring:
  application:
    name: userservice
  server:
    port: 8081
  datasource:
    url:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#  datasource:
#    url: jdbc:postgresql://your_host:5432/your_postgres_db
#    username: your_pg_username
#    password: your_pg_password
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


