spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation
    rabbitmq:
      host: localhost
      port: 15672
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8083

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: acitivity.queue
  routing:
    key: acitvity.tracking
